# Generated by Django 3.0.3 on 2022-02-28 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('shiny', models.BooleanField()),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
